### ISSUE TITLE
Atualizar rotas para utilizar o atributo Route

### ISSUE THREAD

**Issue by chicobentojr** [Projeto-SIAC/siac#31]
**Checklist**
- [ ] Academica
- [ ] Acesso
- [ ] Agenda
- [ ] Arquivo
- [ ] Autoavaliacao
- [ ] Candidato
- [ ] Certificacao
- [ ] Configuracoes
- [ ] Erro
- [ ] Gerencia
- [ ] Historico
- [ ] Impressao
- [ ] Inscricao
- [ ] Institucional
- [ ] Perfil
- [ ] Principal
- [ ] Questao
- [ ] Reposicao
- [ ] Simulado
- [ ] Tema
- [ ] Usuario
- [ ] Visitante

**Comment by chicobentojr** [comment]
- [x] Transferir rotas pras `actions`

**Comment by felipemfp** [comment]
A ideia é criar melhores URLs utilizando o atributo Route. Com isso, precisamos atualizar os módulos .js para utilizar URLs fornecidas pela View (como já está desenvolvido com o SimuladoController).

**Comment by chicobentojr** [comment]
Essa forma será utilizada no core, não?

**Comment by felipemfp** [comment]
Sim, também.

**Comment by felipemfp** [comment]
Será feito na migração para ASP.NET Core.

**Comment by felipemfp** [comment]
O projeto não chegar à uma versão 3. Uma nova abordagem será analisada.
